import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';

// Generated by the installation but not used.
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}
